AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 10

Resources:
  createReviewFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: review/
      PackageType: Image
      Architectures:
        - x86_64
      Environment:
        Variables:
          SECRET_KEY:
          PORT_PG:
          DB_PG:
          HOST_PG:
          USER_PG:
          PASSWORD_PG:
      Events:
        ApiEvent:
          Type: HttpApi
        Api:
          Type: Api
          Properties:
            Path: /reviews
            Method: post
    Metadata:
      DockerTag: go1.x-v1
      DockerContext: ./review
      Dockerfile: Dockerfile
  createProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: product/
      PackageType: Image
      Architectures:
        - x86_64
      Environment:
        Variables:
          SECRET_KEY: "ihaveasecret"
          PORT_PG: 5432
          DB_PG: "fheicxgc"
          HOST_PG: "salt.db.elephantsql.com"
          USER_PG: "fheicxgc"
          PASSWORD_PG: "SK5m_1h39TeSwei_AE14Ra3ChpsdG_aT"
      Events:
        ApiEvent:
          Type: HttpApi
        Api:
          Type: Api
          Properties:
            Path: /products
            Method: post
    Metadata:
      DockerTag: go1.x-v1
      DockerContext: ./product
      Dockerfile: Dockerfile
  createProductTypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: product-type/
      PackageType: Image
      Architectures:
        - x86_64
      Environment:
        Variables:
          SECRET_KEY: "ihaveasecret"
          PORT_PG: 5432
          DB_PG: "fheicxgc"
          HOST_PG: "salt.db.elephantsql.com"
          USER_PG: "fheicxgc"
          PASSWORD_PG: "SK5m_1h39TeSwei_AE14Ra3ChpsdG_aT"
      Events:
        ApiEvent:
          Type: HttpApi
        Api:
          Type: Api
          Properties:
            Path: /types
            Method: post
    Metadata:
      DockerTag: go1.x-v1
      DockerContext: ./product-type
      Dockerfile: Dockerfile
