version: "3.3"
services:
  pg_main:
    build:
      dockerfile: ./compose/postgres/Write/Dockerfile
      context: .
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: reviews-camera
      PG_REP_USER: replicator
      PG_REP_PASSWORD: 123456
    volumes:
      - ./compose/postgres/Write/pg_hba_example.conf:/etc/postgresql/pg_ident.conf
      - ./compose/postgres/Write/postgresql_example.conf:/etc/postgresql/postgresql.conf
    ports:
      - 5436:5432
    networks:
      default:
        aliases:
          - pg_cluster
  # pg_replica:
  #   build:
  #     dockerfile: ./compose/postgres/Read/Dockerfile
  #     context: .
  #   restart: always
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: example
  #     POSTGRES_DB: reviews-camera
  #     PG_REP_USER: rep
  #     PG_REP_PASSWORD: 123456
  #     PG_MASTER_HOST: pg_main
  #   ports:
  #     - 5432:5432
  #   networks:
  #     default:
  #       aliases:
  #         - pg_cluster
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - 8000:80
