CREATE DATABE "reviews-camera"
  WITH
  OWNER = postgres
  ENCODING = 'UTF8'
  LC_COLLATE = 'en_US.utf8'
  LC_CTYPE = 'en_US.utf8'
  TABLESPACE = pg_default
  CONNECTION lIMIT = -1

CREATE ROLE "user-read" WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:+7kRbSl1jxpVP2ckDVFgSg==$yE8iK5jx+ZD1L1uyKenEwBVVMzsV2966bWjAQWXPIkg=:MDEtzWmAJFqzp6p5d9IBk5qRiyqpvsXcyvnCqt9btDk=';
