##
# Makefile for EC2 one server only for requests
#
# @file
# @version 0.1

# end

development-local:
	PORT_PG=5436 HOST_PG=localhost DB_PG=reviews-camera USER_PG=user_read PASSWORD_PG=user_read go run ./main.go
