AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 10

Resources:
  signupFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: "signup/"
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: "Api"
          Properties:
            Path: "/signup"
            Method: "post"
    Metadata:
      DockerTag: go1.x-v1
      DockerContext: ./signup
      Dockerfile: Dockerfile
  # loginFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: "authenticate/"
  #     PackageType: Image
  #     Architectures:
  #       - x86_64
  #     Events:
  #       CatchAll:
  #         Type: "Api"
  #         Properties:
  #           Path: "/login"
  #           Method: "post"
  #   Metadata:
  #     DockerTag: go1.x-v1
  #     DockerContext: ./authenticate
  #     Dockerfile: Dockerfile
